name: mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.2.0
  permission_handler: ^11.3.1
  dio: ^5.7.0
  flutter_riverpod: ^2.5.1
  socket_io_client: ^2.0.3+1
  # (We will speak mediasoup via Socket.IO as we did in signaling.)
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
